### ISSUE TITLE
Feature Request: PHP and LESS

### ISSUE THREAD

**Issue by TomMalbran** [peterflynn/reasonable-comments#1]
Could you add clike and less to the supported languages? I want this feature to work in PHP and LESS too.

Or maybe just check if the block comment prefix is `/*` and suffix is `*/` to support all the languages that support this multiple lines comments at once.

Thanks :)

**Comment by taylorthurlow** [comment]
Yeah, "/**" comment blocks with PHP would be lovely.

**Comment by peterflynn** [comment]
Fixed in version 1.2 -- thanks @TomMalbran for spurring this into action!

**Comment by peterflynn** [comment]
Note: version 1.3 generalizes this to support any registered language with `/*`-style comments

**Comment by TomMalbran** [comment]
Awesome. Thanks
